name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Get Changelog Information
      id: changelog
      run: |
        set -o pipefail

        version=$(sed -e 's;^##\s\+\[\(v[0-9.]\+\)\].*;\1; p ; d' CHANGELOG.md | head -n 1)

        (
          echo "Full changelog ⇒ [$version](https://github.com/${{ github.repository }}/blob/$version/CHANGELOG.md)"

          awk -v version="$version" '
            /^##\s+\[.*?\]\s/ && $2 != "[" version "]" {
              inside = 0;
            }
            inside && (inside == 2 || $0) {
              gsub(/^#/, "");
              print;
              if ($0) { inside = 2; }
            }
            /^##\s+\[.*?\]\s/ && $2 == "[" version "]" {
             inside = 1;
            }' CHANGELOG.md | \
            sed -Ez '$ s/\n+$/\n/'
        ) >releasenotes.md

        echo "version=$version" >>"$GITHUB_OUTPUT"

    - id: create_release
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.sha }}
        tag: ${{ steps.changelog.outputs.version }}
        bodyFile: releasenotes.md
        draft: false
        allowUpdates: true
        updateOnlyUnreleased: true

    - name: Create Summary
      run: |
        echo "Release: ${{ steps.create_release.outputs.html_url }}" >>"$GITHUB_STEP_SUMMARY"
