name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Get Changelog Information
      id: changelog
      run: |
        version_date=$(sed -e 's;^##\s\+\[\(v[0-9.]\+\)\]\(\s\|-\)*\([0-9-]\+\);\1 \3; p ; d' CHANGELOG.md | head -n 1)
        version=${version_date% *}
        date=${version_date#* }
        echo "version=$version" >>"$GITHUB_OUTPUT"
        echo "url=https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md#${version//./}---$date" >>"$GITHUB_OUTPUT"

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.ref }}
        tag_name: ${{ steps.changelog.outputs.version }}
        body: |
          Full changelog ⇒ [${{ steps.extract.outputs.version }}](${{ steps.extract.outputs.url }})
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true
