name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Get Changelog Information
      id: changelog
      run: |
        set -o pipefail

        version=$(sed -e 's;^##\s\+\[\(v[0-9.]\+\)\].*;\1; p ; d' CHANGELOG.md | head -n 1)

        echo "version=$version" >>"$GITHUB_OUTPUT"
        echo "url=https://github.com/${{ github.repository }}/blob/$version/CHANGELOG.md" >>"$GITHUB_OUTPUT"

    - id: create_release
      name: Create Release
      uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.sha }}
        tag: ${{ steps.changelog.outputs.version }}
        body: |
          Full changelog ⇒ [${{ steps.changelog.outputs.version }}](${{ steps.changelog.outputs.url }})
        draft: true
        allowUpdates: true
        updateOnlyUnreleased: true

    - name: Create Summary
      run: |
        echo "Release: ${{ steps.create_release.outputs.html_url }}" >>"$GITHUB_STEP_SUMMARY"
