name: Sync Submodule Dependencies

on:
  push:
    branches:
    - master
    paths:
    - "deps/*_*/**"
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set Up Workspace
      # Submodules shouldn't cause a download.
      run: |
        set -o pipefail
        go work init . $(ls ./deps/*_*/cgo.go | xargs -r dirname)

    - id: info
      name: Extract Information
      run: |
        set -o pipefail
        submods=(
          $(find deps -maxdepth 2 -type f -name libmanifest | \
              xargs -r dirname | \
              xargs -rn1 basename | \
              while read os_arch; do
                echo "deps/$os_arch"
              done)
        )

        # This is the latest commit affecting any file in the submodules.
        # Thus, this workflow is idempotent.
        sha="$(git log -n 1 --pretty=format:%H -- "${submods[@]}")"

        echo "submodules=${submods[*]}" >>"$GITHUB_OUTPUT"
        echo "sha=$sha" >>"$GITHUB_OUTPUT"
        echo "short-sha=${sha::8}" >>"$GITHUB_OUTPUT"

    - name: Update go.mod
      run: |
        sha="${{ steps.info.outputs.sha }}"
        submods=( $(for submod in ${{ steps.info.outputs.submodules }}; do echo "github.com/${{ github.repository }}/$submod@$sha" ; done) )
        go get "${submods[@]}"

    - id: create_pr
      name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
          commit-message: Bump go.mod to latest submodules (${{ steps.info.outputs.short-sha }})
          title: Bump go.mod to latest submodules (${{ steps.info.outputs.short-sha }})
          body: Auto-generated pull request from workflows/syncsubdeps.
          add-paths: |
              go.mod
              go.sum
          branch: workflow/syncsubdeps
          delete-branch: true

    - name: Create Summary
      run: |
          echo "PR: ${{ steps.create_pr.outputs.pull-request-url }}" >>"$GITHUB_STEP_SUMMARY"
